version: '3.7'

services:
  geth-rpc-endpoint:
    hostname: geth-rpc-endpoint
    env_file:
      - .env
    image: geth-client
    build:
      context: .
      args:
        - ACCOUNT_PASSWORD=${ACCOUNT_PASSWORD}   
    command:
      --allow-insecure-unlock
      --http
      --http.addr="0.0.0.0"
      --http.api="eth,web3,net,admin,personal,txpool"
      --http.corsdomain="*"
      --networkid=${NETWORK_ID}
    ports:
      - "8545:8545"
    networks:
      priv-eth-net:


networks:
  priv-eth-net:
    driver: bridge