version: '3.7'

services:
  geth-miner:
    hostname: geth-miner
    env_file:
      - .env
    image: geth-client
    build:
      context: .
      args:
        - ACCOUNT_PASSWORD=${ACCOUNT_PASSWORD}
    command:
      --mine
      --miner.threads=1
      --networkid=${NETWORK_ID}

    networks:
      priv-eth-net:

networks:
  priv-eth-net:
    driver: bridge